# 游戏配置
obs:
  mode: "virtual_cam"  # virtual_cam/window/screen
  camera_index: 2      # 虚拟摄像头设备索引 0、1、2

game:
  window_title: "OBS 30.2.2"  # 仅window模式需要
  region: [0, 0, 1280, 720]  # 捕获区域，所有模式都可能用到
  classes:  # 游戏内目标类别
    0: monster_normal  # 普通小怪，数量多、体型中等、生命值低
    1: monster_elite   # 精英怪，体型较大、带有特殊光效或标识、攻击力高
    2: monster_boss    # BOSS级怪物，体型巨大、有独特模型/特效、通常位于固定区域
    3: npc_friendly    # 友好NPC，通常站立不动、头顶有感叹号/问号等交互标识、
    4: ui_button       # 游戏界面按钮（如任务提交、商店等），有固定位置和标准UI样式
    5: item_health     # 血瓶/治疗物品，通常为红色瓶状或十字标志
    6: item_mana       # 蓝瓶/魔法物品，通常为蓝色瓶状或魔法符文
    7: minimap_marker  # 小地图上的路径点/任务标记，通常为黄色箭头或特殊图标

# 性能配置
performance:
  target_fps: 60
  max_cpu_usage: 85
  dynamic_detection: true  # 动态调整检测频率

# YOLOv5模型配置
yolo:
  weights_path: "data/weights/best.pt"
  device: "cuda:0"  # 自动选择
  img_size: 640
  conf_thres: 0.7
  iou_thres: 0.45

# 战斗系统
combat:
  skill_keys: ["1", "2", "3", "4"]   #在combat.py中的技能释放逻辑
  potion_key: "q"  #药水键
  min_health: 0.3  # 血量低于30%撤退
  max_combat_duration: 120  # 最大战斗持续时间(秒)
  target_priority: [2, 1, 0]  # 优先攻击BOSS → 精英 → 小怪

# 导航系统
navigation:
  move_keys: ["w", "a", "s", "d"]
  move_duration: 0.5  # 基础移动持续时间(秒)
  stuck_threshold: 5  # 卡住检测帧数

antidetection:
  delays:
    move: 0.15    # 移动操作基础延迟(秒)
    skill: 0.3    # 技能释放延迟
    turn: 0.25    # 转向延迟
  mouse_jitter: 2 # 鼠标移动抖动像素范围