# 游戏目标检测优化版 (文件名: game_yolov5s.yaml)
# 主要优化点：
# 1. 调整锚点框适应游戏UI元素
# 2. 增强小目标检测能力
# 3. 优化推理速度

nc: 8  # 游戏目标类别数 (例如: 怪物/NPC/道具等)
depth_multiple: 0.33
width_multiple: 0.50

# 优化后的锚点框 (根据游戏目标统计得出)
anchors:
  - [6,8,  12,15,  20,25]      # 小UI元素
  - [30,40,  50,60,  80,90]     # 角色/怪物
  - [120,160,  200,250,  350,400] # 大型BOSS

backbone:
  # 使用更轻量的结构
  [[-1, 1, Focus, [64, 3]],
  [[-1, 1, Conv, [128, 3, 2]],
  [[-1, 3, C3, [128]],
  [[-1, 1, Conv, [256, 3, 2]],
  [[-1, 6, C3, [256]],
  [[-1, 1, Conv, [384, 3, 2]],  # 比标准版减少通道数
  [[-1, 6, C3, [384]],
  [[-1, 1, Conv, [512, 3, 2]],
  [[-1, 3, C3, [512]],
  [[-1, 1, SPPF, [512, 5]],     # 减小特征图尺寸

head:
  # 增强小目标检测
  [[-1, 1, Conv, [256, 1, 1]],
  [[-1, 1, nn.Upsample, [None, 2, 'nearest']],
  [[-6, 1, Conv, [256, 1, 1]],
  [[-2, -1], 1, Concat, [1]],
  [[-1, 3, C3, [256, False]],

  [[-1, 1, Conv, [128, 1, 1]],
  [[-1, 1, nn.Upsample, [None, 2, 'nearest']],
  [[-13, 1, Conv, [128, 1, 1]],
  [[-2, -1], 1, Concat, [1]],
  [[-1, 3, C3, [128, False]],

  [[-1, 1, Conv, [128, 3, 2]],
  [[-1, -11], 1, Concat, [1]],
  [[-1, 3, C3, [256, False]],

  [[-1, 1, Conv, [256, 3, 2]],
  [[-1, -7], 1, Concat, [1]],
  [[-1, 3, C3, [384, False]],

  [[[17, 20, 23], 1, Detect, [nc, anchors]],